# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe-bundler", ">0.0.0", :group => [:development, :test]
gem "rspec", ">0.0.0", :group => [:development, :test]
#gem "ZenTest", ">0.0.0", :group => [:development, :test]
gem "cucumber", ">0.0.0", :group => [:development, :test]
gem "aruba", ">0.0.0", :group => [:development, :test]
gem "vcr", ">0.0.0", :group => [:development, :test]
gem "webmock", ">0.0.0", :group => [:development, :test]
gem "mechanize", ">0.0.0", :group => [:development, :test]
gem "guard", ">0.0.0", :group => [:development, :test]
gem "guard-rspec", ">0.0.0", :group => [:development, :test]
gem "hoe", "~>3.7", :group => [:development, :test]

# vim: syntax=ruby
